" GENERATED by themes/hestia/render.py from palette.yml v0.10.1 + scopes.yml — do not edit; edit the sources and re-render
" hestia.vim — hestia's editor colorscheme (Vim + Neovim). Inspired by the
" wildcharm scheme (Maxim Kim); hestia owns it now — the palette was derived
" from wildcharm, so the look is unchanged save hestia's documented deviations
" (comment/purple/diff-delete on the dark syntax roles; the AA-tuned light
" values). Vim and Neovim render identically. Edit palette.yml + re-render.

hi clear
if has('nvim')
  " match Vim's default group baseline so unset groups agree across editors
  silent! source $VIMRUNTIME/colors/vim.lua
endif
let g:colors_name = 'hestia'

let s:t_Co = has('gui_running') ? -1 : (&t_Co ?? 0)

hi! link Terminal Normal
hi! link StatuslineTerm Statusline
hi! link StatuslineTermNC StatuslineNC
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link MessageWindow Pmenu
hi! link PopupNotification Todo
hi! link PopupSelected PmenuSel
hi! link CurSearch IncSearch

" treesitter / LSP captures -> standard groups (nvim parity with Vim).
" Nvim-ONLY: Vim has no treesitter, and older Vim patchlevels reject the
" @ in these group names (W18) — so guard the whole block on has('nvim').
if has('nvim')
  hi! link @comment Comment
  hi! link @comment.documentation Comment
  hi! link @comment.todo Todo
  hi! link @comment.note Todo
  hi! link @comment.warning Todo
  hi! link @comment.error Error
  hi! link @constant Constant
  hi! link @constant.builtin hestiaBuiltinConst
  hi! link @constant.macro PreProc
  hi! link @number Constant
  hi! link @number.float Constant
  hi! link @boolean hestiaBuiltinConst
  hi! link @character Constant
  hi! link @character.special Special
  hi! link @string String
  hi! link @string.documentation String
  hi! link @string.escape Special
  hi! link @string.regexp Special
  hi! link @string.special Special
  hi! link @string.special.symbol Constant
  hi! link @string.special.url Underlined
  hi! link @string.special.path Underlined
  hi! link @keyword Statement
  hi! link @conditional Statement
  hi! link @repeat Statement
  hi! link @label Statement
  hi! link @exception Statement
  hi! link @include PreProc
  hi! link @keyword.import PreProc
  hi! link @type.qualifier Statement
  hi! link @operator Statement
  hi! link @punctuation Normal
  hi! link @punctuation.delimiter Normal
  hi! link @punctuation.bracket Normal
  hi! link @punctuation.special Special
  hi! link @function Function
  hi! link @function.builtin hestiaBuiltinFunc
  hi! link @function.call Function
  hi! link @function.method Function
  hi! link @function.method.call Function
  hi! link @function.macro PreProc
  hi! link @constructor Function
  hi! link @type Type
  hi! link @type.builtin hestiaBuiltinType
  hi! link @type.definition Type
  hi! link @attribute PreProc
  hi! link @attribute.builtin PreProc
  hi! link @variable Normal
  hi! link @variable.builtin hestiaSelf
  hi! link @variable.parameter hestiaParam
  hi! link @variable.member Normal
  hi! link @property Normal
  hi! link @field Normal
  hi! link @module Normal
  hi! link @module.builtin Normal
  hi! link @namespace Normal
  hi! link @tag Statement
  hi! link @tag.attribute Type
  hi! link @tag.delimiter Normal
  hi! link @markup.link.url Underlined
  hi! link @markup.raw String
  hi! link @lsp.type.namespace Normal
  hi! link @lsp.type.variable Normal
  hi! link @lsp.type.property Normal
  hi! link @lsp.type.parameter Normal
endif

if &background ==# 'dark'
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#000000', '#d7005f', '#00af5f', '#d78700', '#0087d7', '#d787d7', '#00afaf', '#d0d0d0', '#767676', '#ff5f87', '#00d75f', '#ffaf00', '#00afff', '#ff87ff', '#00d7d7', '#ffffff']
    if has('nvim')
      for s:i in range(len(g:terminal_ansi_colors)) | let g:terminal_color_{s:i} = g:terminal_ansi_colors[s:i] | endfor
    endif
  endif
  hi Normal guifg=#e0e0e0 guibg=#1a1a1a gui=NONE cterm=NONE
  hi Statusline guifg=#ffffff guibg=#7c3aed gui=bold cterm=bold
  hi StatuslineNC guifg=#767676 guibg=#1a1a1a gui=reverse cterm=reverse
  hi VertSplit guifg=#767676 guibg=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#000000 guibg=#767676 gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#1a1a1a gui=NONE cterm=NONE
  hi TabLineSel guifg=#000000 guibg=#9e9e9e gui=bold cterm=bold
  hi ToolbarLine guifg=NONE guibg=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#000000 guibg=#d0d0d0 gui=NONE cterm=NONE
  hi QuickFixLine guifg=#000000 guibg=#f840ac gui=NONE cterm=NONE
  hi CursorLineNr guifg=#ffffff guibg=NONE gui=bold cterm=bold
  hi LineNr guifg=#585858 guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#585858 guibg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#585858 guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#585858 guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#767676 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#d0d0d0 guibg=#303030 gui=NONE cterm=NONE
  hi PmenuSel guifg=#d0d0d0 guibg=#585858 gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#d0d0d0 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=NONE gui=NONE cterm=NONE
  hi PmenuKind guifg=#9e77f7 guibg=#303030 gui=NONE cterm=NONE
  hi PmenuKindSel guifg=#9e77f7 guibg=#585858 gui=NONE cterm=NONE
  hi PmenuExtra guifg=#767676 guibg=#303030 gui=NONE cterm=NONE
  hi PmenuExtraSel guifg=#767676 guibg=#585858 gui=NONE cterm=NONE
  hi PmenuMatch guifg=#f725a0 guibg=#303030 gui=NONE cterm=NONE
  hi PmenuMatchSel guifg=#f725a0 guibg=#585858 gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#d70000 guibg=#ffffff gui=reverse cterm=reverse
  hi ErrorMsg guifg=#d70000 guibg=#ffffff gui=reverse cterm=reverse
  hi ModeMsg guifg=NONE guibg=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#3ab953 guibg=NONE gui=NONE cterm=NONE
  hi Question guifg=#fa74c2 guibg=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#ffaf00 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#9e77f7 guibg=#1a1a1a gui=reverse cterm=reverse
  hi Search guifg=#000000 guibg=#32a148 gui=NONE cterm=NONE
  hi IncSearch guifg=#000000 guibg=#e0a020 gui=NONE cterm=NONE
  hi WildMenu guifg=#000000 guibg=#e0a020 gui=NONE cterm=NONE
  hi debugPC guifg=#4a8fe4 guibg=NONE gui=reverse cterm=reverse
  hi debugBreakpoint guifg=#0cb2c0 guibg=NONE gui=reverse cterm=reverse
  hi Cursor guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi lCursor guifg=#000000 guibg=#ff5fff gui=NONE cterm=NONE
  hi Visual guifg=#5fd7ff guibg=#000000 gui=reverse cterm=reverse
  hi VisualNOS guifg=#000000 guibg=#4a8fe4 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#262626 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#262626 gui=NONE cterm=NONE
  hi Folded guifg=#767676 guibg=#303030 gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#303030 gui=NONE cterm=NONE
  hi MatchParen guifg=#ff00af guibg=NONE gui=bold cterm=bold
  hi SpellBad guifg=NONE guibg=NONE guisp=#ff4f38 gui=undercurl cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#0cb2c0 gui=undercurl cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#2f9844 gui=undercurl cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#fa74c2 gui=undercurl cterm=undercurl
  hi Comment guifg=#8c8c8c guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#ff4f38 guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#32a148 guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#f840ac guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#4a8fe4 guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#e0a020 guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#0cb2c0 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#9e77f7 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE gui=underline cterm=underline
  hi Title guifg=NONE guibg=NONE gui=bold cterm=bold
  hi Directory guifg=#4a8fe4 guibg=NONE gui=bold cterm=bold
  hi Conceal guifg=#585858 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=NONE guibg=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#163a20 gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#14303f gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#1d4a63 gui=bold cterm=bold
  hi DiffDelete guifg=#ff4f38 guibg=#431624 gui=NONE cterm=NONE
  hi Added guifg=#32a148 guibg=NONE gui=NONE cterm=NONE
  hi Changed guifg=#4a8fe4 guibg=NONE gui=NONE cterm=NONE
  hi Removed guifg=#ff4f38 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticError guifg=#9e77f7 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticWarn guifg=#ffaf00 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticInfo guifg=#00afff guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticHint guifg=#22cdda guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticOk guifg=#3ab953 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#9e77f7 gui=undercurl cterm=undercurl
  hi DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#ffaf00 gui=undercurl cterm=undercurl
  hi DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#00afff gui=undercurl cterm=undercurl
  hi DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#22cdda gui=undercurl cterm=undercurl
  hi hestiaBuiltinFunc guifg=#f840ac guibg=NONE gui=italic cterm=italic
  hi hestiaBuiltinConst guifg=#ff4f38 guibg=NONE gui=italic cterm=italic
  hi hestiaBuiltinType guifg=#e0a020 guibg=NONE gui=italic cterm=italic
  hi hestiaParam guifg=#e0e0e0 guibg=NONE gui=italic cterm=italic
  hi hestiaSelf guifg=#ff4f38 guibg=NONE gui=italic cterm=italic
else
  if (has('termguicolors') && &termguicolors) || has('gui_running')
    let g:terminal_ansi_colors = ['#000000', '#af0000', '#008700', '#af5f00', '#005faf', '#870087', '#008787', '#8a8a8a', '#808080', '#d70000', '#5faf5f', '#d78700', '#0087d7', '#af00af', '#00afaf', '#ffffff']
    if has('nvim')
      for s:i in range(len(g:terminal_ansi_colors)) | let g:terminal_color_{s:i} = g:terminal_ansi_colors[s:i] | endfor
    endif
  endif
  hi Normal guifg=#1a1a1a guibg=#f5f5f5 gui=NONE cterm=NONE
  hi Statusline guifg=#ffffff guibg=#7c3aed gui=bold cterm=bold
  hi StatuslineNC guifg=#000000 guibg=#dadada gui=NONE cterm=NONE
  hi VertSplit guifg=#5f5f5f guibg=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#000000 guibg=#dadada gui=NONE cterm=NONE
  hi TabLineFill guifg=NONE guibg=#f5f5f5 gui=NONE cterm=NONE
  hi TabLineSel guifg=#ffffff guibg=#5f5f5f gui=bold cterm=bold
  hi ToolbarLine guifg=NONE guibg=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#ffffff guibg=#5f5f5f gui=NONE cterm=NONE
  hi QuickFixLine guifg=#ffffff guibg=#c60777 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#000000 guibg=NONE gui=bold cterm=bold
  hi LineNr guifg=#b2b2b2 guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#b2b2b2 guibg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#b2b2b2 guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#b2b2b2 guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#b2b2b2 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#000000 guibg=#e4e4e4 gui=NONE cterm=NONE
  hi PmenuSel guifg=#000000 guibg=#dadada gui=NONE cterm=NONE
  hi PmenuThumb guifg=NONE guibg=#808080 gui=NONE cterm=NONE
  hi PmenuSbar guifg=NONE guibg=NONE gui=NONE cterm=NONE
  hi PmenuKind guifg=#cc1800 guibg=#e4e4e4 gui=NONE cterm=NONE
  hi PmenuKindSel guifg=#cc1800 guibg=#dadada gui=NONE cterm=NONE
  hi PmenuExtra guifg=#808080 guibg=#e4e4e4 gui=NONE cterm=NONE
  hi PmenuExtraSel guifg=#808080 guibg=#dadada gui=NONE cterm=NONE
  hi PmenuMatch guifg=#c60777 guibg=#e4e4e4 gui=NONE cterm=NONE
  hi PmenuMatchSel guifg=#c60777 guibg=#dadada gui=NONE cterm=NONE
  hi SignColumn guifg=NONE guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#d70000 guibg=#ffffff gui=reverse cterm=reverse
  hi ErrorMsg guifg=#d70000 guibg=#ffffff gui=reverse cterm=reverse
  hi ModeMsg guifg=NONE guibg=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#237133 guibg=NONE gui=NONE cterm=NONE
  hi Question guifg=#be0772 guibg=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#af5f00 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#733af4 guibg=#f5f5f5 gui=reverse cterm=reverse
  hi Search guifg=#ffffff guibg=#247534 gui=NONE cterm=NONE
  hi IncSearch guifg=#ffffff guibg=#855f12 gui=NONE cterm=NONE
  hi WildMenu guifg=#ffffff guibg=#855f12 gui=NONE cterm=NONE
  hi debugPC guifg=#1c65bd guibg=NONE gui=reverse cterm=reverse
  hi debugBreakpoint guifg=#076d76 guibg=NONE gui=reverse cterm=reverse
  hi Cursor guifg=#ffffff guibg=#000000 gui=NONE cterm=NONE
  hi lCursor guifg=#000000 guibg=#ff00ff gui=NONE cterm=NONE
  hi Visual guifg=#0087d7 guibg=#ffffff gui=reverse cterm=reverse
  hi VisualNOS guifg=#ffffff guibg=#1c65bd gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#e4e4e4 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#e4e4e4 gui=NONE cterm=NONE
  hi Folded guifg=#808080 guibg=#e4e4e4 gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#e4e4e4 gui=NONE cterm=NONE
  hi MatchParen guifg=#ff00af guibg=NONE gui=bold cterm=bold
  hi SpellBad guifg=NONE guibg=NONE guisp=#cc1800 gui=undercurl cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#076d76 gui=undercurl cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#237133 gui=undercurl cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#d40880 gui=undercurl cterm=undercurl
  hi Comment guifg=#6c6c6c guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#cc1800 guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#247534 guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#c60777 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#1c65bd guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#855f12 guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#08717a guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#733af4 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE gui=underline cterm=underline
  hi Title guifg=NONE guibg=NONE gui=bold cterm=bold
  hi Directory guifg=#1c65bd guibg=NONE gui=bold cterm=bold
  hi Conceal guifg=#b2b2b2 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=NONE guibg=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=NONE guibg=#d3efdb gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#d6e7f4 gui=NONE cterm=NONE
  hi DiffText guifg=NONE guibg=#b3d4ec gui=bold cterm=bold
  hi DiffDelete guifg=#cc1800 guibg=#f6d7de gui=NONE cterm=NONE
  hi Added guifg=#247534 guibg=NONE gui=NONE cterm=NONE
  hi Changed guifg=#1c65bd guibg=NONE gui=NONE cterm=NONE
  hi Removed guifg=#cc1800 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticError guifg=#d70000 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticWarn guifg=#af5f00 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticInfo guifg=#005faf guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticHint guifg=#076d76 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticOk guifg=#237133 guibg=NONE gui=NONE cterm=NONE
  hi DiagnosticUnderlineError guifg=NONE guibg=NONE guisp=#d70000 gui=undercurl cterm=undercurl
  hi DiagnosticUnderlineWarn guifg=NONE guibg=NONE guisp=#af5f00 gui=undercurl cterm=undercurl
  hi DiagnosticUnderlineInfo guifg=NONE guibg=NONE guisp=#005faf gui=undercurl cterm=undercurl
  hi DiagnosticUnderlineHint guifg=NONE guibg=NONE guisp=#076d76 gui=undercurl cterm=undercurl
  hi hestiaBuiltinFunc guifg=#c60777 guibg=NONE gui=italic cterm=italic
  hi hestiaBuiltinConst guifg=#cc1800 guibg=NONE gui=italic cterm=italic
  hi hestiaBuiltinType guifg=#855f12 guibg=NONE gui=italic cterm=italic
  hi hestiaParam guifg=#1a1a1a guibg=NONE gui=italic cterm=italic
  hi hestiaSelf guifg=#cc1800 guibg=NONE gui=italic cterm=italic
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    hi Normal ctermfg=254 ctermbg=234 cterm=NONE
    hi Statusline ctermfg=231 ctermbg=99 cterm=bold
    hi StatuslineNC ctermfg=243 ctermbg=234 cterm=reverse
    hi VertSplit ctermfg=243 ctermbg=NONE cterm=NONE
    hi TabLine ctermfg=16 ctermbg=243 cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=234 cterm=NONE
    hi TabLineSel ctermfg=16 ctermbg=247 cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ToolbarButton ctermfg=16 ctermbg=252 cterm=NONE
    hi QuickFixLine ctermfg=16 ctermbg=205 cterm=NONE
    hi CursorLineNr ctermfg=231 ctermbg=NONE cterm=bold
    hi LineNr ctermfg=240 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=240 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=240 ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=240 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=243 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=252 ctermbg=236 cterm=NONE
    hi PmenuSel ctermfg=252 ctermbg=240 cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=252 cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=NONE
    hi PmenuKind ctermfg=141 ctermbg=236 cterm=NONE
    hi PmenuKindSel ctermfg=141 ctermbg=240 cterm=NONE
    hi PmenuExtra ctermfg=243 ctermbg=236 cterm=NONE
    hi PmenuExtraSel ctermfg=243 ctermbg=240 cterm=NONE
    hi PmenuMatch ctermfg=199 ctermbg=236 cterm=NONE
    hi PmenuMatchSel ctermfg=199 ctermbg=240 cterm=NONE
    hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Error ctermfg=160 ctermbg=231 cterm=reverse
    hi ErrorMsg ctermfg=160 ctermbg=231 cterm=reverse
    hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=71 ctermbg=NONE cterm=NONE
    hi Question ctermfg=211 ctermbg=NONE cterm=NONE
    hi WarningMsg ctermfg=214 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=141 ctermbg=234 cterm=reverse
    hi Search ctermfg=16 ctermbg=71 cterm=NONE
    hi IncSearch ctermfg=16 ctermbg=178 cterm=NONE
    hi WildMenu ctermfg=16 ctermbg=178 cterm=NONE
    hi debugPC ctermfg=68 ctermbg=NONE cterm=reverse
    hi debugBreakpoint ctermfg=37 ctermbg=NONE cterm=reverse
    hi Cursor ctermfg=16 ctermbg=231 cterm=NONE
    hi lCursor ctermfg=16 ctermbg=207 cterm=NONE
    hi Visual ctermfg=81 ctermbg=16 cterm=reverse
    hi VisualNOS ctermfg=16 ctermbg=68 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=235 cterm=NONE
    hi Folded ctermfg=243 ctermbg=236 cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=236 cterm=NONE
    hi MatchParen ctermfg=199 ctermbg=NONE cterm=bold
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi Comment ctermfg=245 ctermbg=NONE cterm=italic
    hi Constant ctermfg=203 ctermbg=NONE cterm=NONE
    hi String ctermfg=71 ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=205 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=68 ctermbg=NONE cterm=NONE
    hi Type ctermfg=178 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=37 ctermbg=NONE cterm=NONE
    hi Special ctermfg=141 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi Title ctermfg=NONE ctermbg=NONE cterm=bold
    hi Directory ctermfg=68 ctermbg=NONE cterm=bold
    hi Conceal ctermfg=240 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=235 cterm=NONE
    hi DiffChange ctermfg=NONE ctermbg=236 cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=23 cterm=bold
    hi DiffDelete ctermfg=203 ctermbg=235 cterm=NONE
    hi Added ctermfg=71 ctermbg=NONE cterm=NONE
    hi Changed ctermfg=68 ctermbg=NONE cterm=NONE
    hi Removed ctermfg=203 ctermbg=NONE cterm=NONE
    hi DiagnosticError ctermfg=141 ctermbg=NONE cterm=NONE
    hi DiagnosticWarn ctermfg=214 ctermbg=NONE cterm=NONE
    hi DiagnosticInfo ctermfg=39 ctermbg=NONE cterm=NONE
    hi DiagnosticHint ctermfg=44 ctermbg=NONE cterm=NONE
    hi DiagnosticOk ctermfg=71 ctermbg=NONE cterm=NONE
    hi DiagnosticUnderlineError ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineWarn ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineHint ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi hestiaBuiltinFunc ctermfg=205 ctermbg=NONE cterm=italic
    hi hestiaBuiltinConst ctermfg=203 ctermbg=NONE cterm=italic
    hi hestiaBuiltinType ctermfg=178 ctermbg=NONE cterm=italic
    hi hestiaParam ctermfg=254 ctermbg=NONE cterm=italic
    hi hestiaSelf ctermfg=203 ctermbg=NONE cterm=italic
  else
    hi Normal ctermfg=234 ctermbg=255 cterm=NONE
    hi Statusline ctermfg=231 ctermbg=99 cterm=bold
    hi StatuslineNC ctermfg=16 ctermbg=253 cterm=NONE
    hi VertSplit ctermfg=59 ctermbg=NONE cterm=NONE
    hi TabLine ctermfg=16 ctermbg=253 cterm=NONE
    hi TabLineFill ctermfg=NONE ctermbg=255 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=59 cterm=bold
    hi ToolbarLine ctermfg=NONE ctermbg=NONE cterm=NONE
    hi ToolbarButton ctermfg=231 ctermbg=59 cterm=NONE
    hi QuickFixLine ctermfg=231 ctermbg=162 cterm=NONE
    hi CursorLineNr ctermfg=16 ctermbg=NONE cterm=bold
    hi LineNr ctermfg=249 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=249 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=249 ctermbg=NONE cterm=NONE
    hi SpecialKey ctermfg=249 ctermbg=NONE cterm=NONE
    hi EndOfBuffer ctermfg=249 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=16 ctermbg=254 cterm=NONE
    hi PmenuSel ctermfg=16 ctermbg=253 cterm=NONE
    hi PmenuThumb ctermfg=NONE ctermbg=244 cterm=NONE
    hi PmenuSbar ctermfg=NONE ctermbg=NONE cterm=NONE
    hi PmenuKind ctermfg=160 ctermbg=254 cterm=NONE
    hi PmenuKindSel ctermfg=160 ctermbg=253 cterm=NONE
    hi PmenuExtra ctermfg=244 ctermbg=254 cterm=NONE
    hi PmenuExtraSel ctermfg=244 ctermbg=253 cterm=NONE
    hi PmenuMatch ctermfg=162 ctermbg=254 cterm=NONE
    hi PmenuMatchSel ctermfg=162 ctermbg=253 cterm=NONE
    hi SignColumn ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Error ctermfg=160 ctermbg=231 cterm=reverse
    hi ErrorMsg ctermfg=160 ctermbg=231 cterm=reverse
    hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=bold
    hi MoreMsg ctermfg=238 ctermbg=NONE cterm=NONE
    hi Question ctermfg=125 ctermbg=NONE cterm=NONE
    hi WarningMsg ctermfg=130 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=63 ctermbg=255 cterm=reverse
    hi Search ctermfg=231 ctermbg=29 cterm=NONE
    hi IncSearch ctermfg=231 ctermbg=94 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=94 cterm=NONE
    hi debugPC ctermfg=25 ctermbg=NONE cterm=reverse
    hi debugBreakpoint ctermfg=24 ctermbg=NONE cterm=reverse
    hi Cursor ctermfg=231 ctermbg=16 cterm=NONE
    hi lCursor ctermfg=16 ctermbg=201 cterm=NONE
    hi Visual ctermfg=32 ctermbg=231 cterm=reverse
    hi VisualNOS ctermfg=231 ctermbg=25 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=254 cterm=NONE
    hi CursorColumn ctermfg=NONE ctermbg=254 cterm=NONE
    hi Folded ctermfg=244 ctermbg=254 cterm=NONE
    hi ColorColumn ctermfg=NONE ctermbg=254 cterm=NONE
    hi MatchParen ctermfg=199 ctermbg=NONE cterm=bold
    hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi Comment ctermfg=242 ctermbg=NONE cterm=italic
    hi Constant ctermfg=160 ctermbg=NONE cterm=NONE
    hi String ctermfg=29 ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=162 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=25 ctermbg=NONE cterm=NONE
    hi Type ctermfg=94 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=24 ctermbg=NONE cterm=NONE
    hi Special ctermfg=63 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi Title ctermfg=NONE ctermbg=NONE cterm=bold
    hi Directory ctermfg=25 ctermbg=NONE cterm=bold
    hi Conceal ctermfg=249 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=NONE ctermbg=NONE cterm=NONE
    hi DiffAdd ctermfg=NONE ctermbg=194 cterm=NONE
    hi DiffChange ctermfg=NONE ctermbg=189 cterm=NONE
    hi DiffText ctermfg=NONE ctermbg=153 cterm=bold
    hi DiffDelete ctermfg=160 ctermbg=224 cterm=NONE
    hi Added ctermfg=29 ctermbg=NONE cterm=NONE
    hi Changed ctermfg=25 ctermbg=NONE cterm=NONE
    hi Removed ctermfg=160 ctermbg=NONE cterm=NONE
    hi DiagnosticError ctermfg=160 ctermbg=NONE cterm=NONE
    hi DiagnosticWarn ctermfg=130 ctermbg=NONE cterm=NONE
    hi DiagnosticInfo ctermfg=25 ctermbg=NONE cterm=NONE
    hi DiagnosticHint ctermfg=24 ctermbg=NONE cterm=NONE
    hi DiagnosticOk ctermfg=238 ctermbg=NONE cterm=NONE
    hi DiagnosticUnderlineError ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineWarn ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi DiagnosticUnderlineHint ctermfg=NONE ctermbg=NONE cterm=undercurl
    hi hestiaBuiltinFunc ctermfg=162 ctermbg=NONE cterm=italic
    hi hestiaBuiltinConst ctermfg=160 ctermbg=NONE cterm=italic
    hi hestiaBuiltinType ctermfg=94 ctermbg=NONE cterm=italic
    hi hestiaParam ctermfg=234 ctermbg=NONE cterm=italic
    hi hestiaSelf ctermfg=160 ctermbg=NONE cterm=italic
  endif
  unlet s:t_Co
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=reverse
  hi CursorColumn term=NONE
  hi CursorLine term=underline
  hi CursorLineNr term=bold
  hi DiffAdd term=reverse
  hi DiffChange term=NONE
  hi DiffDelete term=reverse
  hi DiffText term=reverse
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,reverse
  hi FoldColumn term=NONE
  hi Folded term=NONE
  hi IncSearch term=bold,reverse,underline
  hi LineNr term=NONE
  hi MatchParen term=bold,underline
  hi ModeMsg term=bold
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=reverse
  hi PmenuSel term=bold
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=reverse
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=underline
  hi SpellCap term=underline
  hi SpellLocal term=underline
  hi SpellRare term=underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=bold,underline
  hi TabLine term=bold,underline
  hi TabLineFill term=NONE
  hi Terminal term=NONE
  hi TabLineSel term=bold,reverse
  hi Title term=NONE
  hi VertSplit term=NONE
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=bold
  hi Constant term=NONE
  hi Error term=bold,reverse
  hi Identifier term=NONE
  hi Ignore term=NONE
  hi PreProc term=NONE
  hi Special term=NONE
  hi Statement term=NONE
  hi Todo term=bold,reverse
  hi Type term=NONE
  hi Underlined term=underline
  unlet s:t_Co
  finish
endif

" vim: et ts=8 sw=2 sts=2
